import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function  About() {

    
  return (
    <div className={styles.container}>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 align="center" >About Page</h1>

      </main>

      <footer className={styles.footer}>
        Footer
      </footer>
    </div>
  )
}
