import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useEffect, useState } from 'react'


export default function Home() {
    const [user, setUser] = useState([])
    useEffect( async ()=>{
        const user = await axios.get(`https://jsonplaceholder.typicode.com/users`);
        setUser(user.data)
    },[])
    console.log(user);

  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 align="center" >Home Page</h1>

        <ol>
            {
                user.map(u => <li key={u.id}>{u.name}</li>)
            }
        </ol>
      </main>

      <footer className={styles.footer}>
        Footer
      </footer>
    </div>
  )
}
